### ISSUE TITLE
Firefox 57+ Quantum Compatibility

### ISSUE THREAD

**Issue by xGSTx** [fuyu/Googalexa#5]
Hi,

I cannot live without this addon. Please make it compatible with Firefox Quantum.

Google PageRank doesn't work anymore so maybe some new functionality instead of it (country flag etc.)

Thank You very much

**Comment by fuyu** [comment]
Hello, yes I'm already looking into new API how to make a new version of extension with it.

**Comment by xGSTx** [comment]
Thank You Sir,

This is an amazing addon. I wish i was intelligent enough to code something like this!

Can't wait for the update :-)

**Comment by lurchpop** [comment]
Please update. This was my favorite plugin!

**Comment by fuyu** [comment]
A version with Quantum support:
https://addons.mozilla.org/en-US/firefox/addon/minimalist-alexa-rank/

Notice the version number is `0.9`, it may contain bugs so give it a try and report as new Issues here.

**Comment by xGSTx** [comment]
Hi,

Thanx for the update! Respect =)

First Bug:

Rank is not visible with Dark Theme on.

Proof:

[https://i.imgur.com/fIH2DGJ.png](url)
