### ISSUE TITLE
Rank not visible in Quantum's new default Dark Theme

### ISSUE THREAD

**Issue by xGSTx** [fuyu/Googalexa#6]
Hi,

First Bug:

Rank is not visible if the new Firefox Dark Theme is on. The color of the URL Bar and the Rank is gray hence rank not visible. You can barely see that the Rank is there if you hover over it with your mouse to highlight the area.

Here you can see the difference. I highlighted the issue in Red. All is good with default light skin (lower half) but not with the Dark Theme on (upper half):

![Image of Bug](https://i.imgur.com/NdwVpt5.png)

[The new default Dark Theme](https://www.ghacks.net/2017/01/16/firefox-new-default-theme-theme-api-makes-an-appearance/) i am talking about now comes as a standard with the new Firefox Quantum. It is NOT a 3rd Party fancy Theme from elsewhere.

So, if the Dark Theme is on the Rank's color needs to be white or light gray. That is basically it.

Thank You very much for making this great Add-On compatible with Quantum.

**Comment by fuyu** [comment]
Thanks, it's a good one. Will look into it.

**Comment by fuyu** [comment]
Version `0.9.1`: added options to configure the text color:
https://addons.mozilla.org/en-US/firefox/addon/minimalist-alexa-rank/

**Comment by xGSTx** [comment]
Thank You Sir!!

It works perfectly now. Best Results with #ffffff
