### ISSUE TITLE
Stop working in FF 60.0

### ISSUE THREAD

**Issue by c3x** [fuyu/Googalexa#7]
In version 60.0 of FF the plugin did not work anymore.

**Comment by fuyu** [comment]
Version 60.0 still works for me. Could you provide more info?

**Comment by c3x** [comment]
It's moved from the address bar to the pulldown and not longer clickable

![acdseeqvpro5_2018-05-14_09-44-23](https://user-images.githubusercontent.com/8462728/39984514-bfd36b8c-575b-11e8-91b6-f8f231ae65cc.jpg)

**Comment by fuyu** [comment]
Closing it as a duplicate: https://github.com/fuyu/alexa-rank-webextension/issues/2
